kind = "web"
previewPath = "/"
title = "NuLife"
version = "1.0.0"
id = "artifacts/nulife"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21241

[services.development]
run = "pnpm --filter @workspace/nulife run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nulife", "run", "build" ]
publicDir = "artifacts/nulife/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21241"
BASE_PATH = "/"
